#%RAML 1.0 SecurityScheme
type: Basic Authentication
description: Authenticate customer by user name and password
describedBy:
  headers:
    userName:
      type: string 
    password:
      type: string
  responses:
    403:
      description: credential is required 
    401:
      description: username or password is incorrect
  

      
      


        



    