#%RAML 1.0 ResourceType

type:
  lib.getCollection:
    response-get-type: lib.customer-dt
    response-get-example: !include ../example/customerEX.json
    error-trait-get: lib.errorResponse

  
            

          
  
      
            
