#%RAML 1.0 ResourceType

type:
  lib.getCollection:
    response-get-type: lib.deliveryPerson-dt
    response-get-example: !include ../example/deliveryPersonEX.json
    error-trait-get: lib.errorResponse
  