#%RAML 1.0 NamedExample

locations: [
                {
                  "address": "Jl. Sultan Iskandar Muda No.21, Arteri Pondok Indah, Pd. Pinang, Kby. Lama, Kota Jakarta Selatan, Daerah Khusus Ibukota Jakarta, Indonesia",
                  "latitude": -6.2608232,
                  "longitude": 106.7884168
                },
                {
                  "address": "Gedung Inti Sentra, Jl. Taman Kemang, RT.14/RW.1, Bangka, Mampang Prpt., Kota Jakarta Selatan, Daerah Khusus Ibukota Jakarta, Indonesia",
                  "latitude": -6.2608232,
                  "longitude": 106.7884168,
                  "need_cod": true,
                  "cod_invoice_fees": 5000,
                  "need_pod":true
                },


              ]