#%RAML 1.0 DataType

type: object
properties:
  driverid: 
    type: integer
  name:
    description: Driver name
    type: string
    maxLength: 35
  contactnumber:
    description: Driver contact phone number
    type: string
    maxLength: 15
  vehicleType:
    type: string
    maxLength: 15




  
  



